// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
namespace pt {
class obj_user_game_record;
struct obj_user_game_recordDefaultTypeInternal;
extern obj_user_game_recordDefaultTypeInternal _obj_user_game_record_default_instance_;
class obj_user_info;
struct obj_user_infoDefaultTypeInternal;
extern obj_user_infoDefaultTypeInternal _obj_user_info_default_instance_;
class req_login;
struct req_loginDefaultTypeInternal;
extern req_loginDefaultTypeInternal _req_login_default_instance_;
class rsp_login;
struct rsp_loginDefaultTypeInternal;
extern rsp_loginDefaultTypeInternal _rsp_login_default_instance_;
}  // namespace pt
PROTOBUF_NAMESPACE_OPEN
template<> ::pt::obj_user_game_record* Arena::CreateMaybeMessage<::pt::obj_user_game_record>(Arena*);
template<> ::pt::obj_user_info* Arena::CreateMaybeMessage<::pt::obj_user_info>(Arena*);
template<> ::pt::req_login* Arena::CreateMaybeMessage<::pt::req_login>(Arena*);
template<> ::pt::rsp_login* Arena::CreateMaybeMessage<::pt::rsp_login>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pt {

enum rsp_login_RET : int {
  rsp_login_RET_SUCCESS = 0,
  rsp_login_RET_ACCOUNT_NULL = 1,
  rsp_login_RET_ACCOUNT_LOCK = 2,
  rsp_login_RET_PASSWORD_ERROR = 3,
  rsp_login_RET_ERROR = 10,
  rsp_login_RET_rsp_login_RET_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  rsp_login_RET_rsp_login_RET_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool rsp_login_RET_IsValid(int value);
constexpr rsp_login_RET rsp_login_RET_RET_MIN = rsp_login_RET_SUCCESS;
constexpr rsp_login_RET rsp_login_RET_RET_MAX = rsp_login_RET_ERROR;
constexpr int rsp_login_RET_RET_ARRAYSIZE = rsp_login_RET_RET_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* rsp_login_RET_descriptor();
template<typename T>
inline const std::string& rsp_login_RET_Name(T enum_t_value) {
  static_assert(::std::is_same<T, rsp_login_RET>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function rsp_login_RET_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    rsp_login_RET_descriptor(), enum_t_value);
}
inline bool rsp_login_RET_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, rsp_login_RET* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<rsp_login_RET>(
    rsp_login_RET_descriptor(), name, value);
}
// ===================================================================

class req_login final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pt.req_login) */ {
 public:
  inline req_login() : req_login(nullptr) {}
  ~req_login() override;
  explicit constexpr req_login(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  req_login(const req_login& from);
  req_login(req_login&& from) noexcept
    : req_login() {
    *this = ::std::move(from);
  }

  inline req_login& operator=(const req_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline req_login& operator=(req_login&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const req_login& default_instance() {
    return *internal_default_instance();
  }
  static inline const req_login* internal_default_instance() {
    return reinterpret_cast<const req_login*>(
               &_req_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(req_login& a, req_login& b) {
    a.Swap(&b);
  }
  inline void Swap(req_login* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(req_login* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  req_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<req_login>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const req_login& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const req_login& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(req_login* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.req_login";
  }
  protected:
  explicit req_login(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:pt.req_login)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class obj_user_info final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pt.obj_user_info) */ {
 public:
  inline obj_user_info() : obj_user_info(nullptr) {}
  ~obj_user_info() override;
  explicit constexpr obj_user_info(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  obj_user_info(const obj_user_info& from);
  obj_user_info(obj_user_info&& from) noexcept
    : obj_user_info() {
    *this = ::std::move(from);
  }

  inline obj_user_info& operator=(const obj_user_info& from) {
    CopyFrom(from);
    return *this;
  }
  inline obj_user_info& operator=(obj_user_info&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const obj_user_info& default_instance() {
    return *internal_default_instance();
  }
  static inline const obj_user_info* internal_default_instance() {
    return reinterpret_cast<const obj_user_info*>(
               &_obj_user_info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(obj_user_info& a, obj_user_info& b) {
    a.Swap(&b);
  }
  inline void Swap(obj_user_info* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(obj_user_info* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  obj_user_info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<obj_user_info>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const obj_user_info& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const obj_user_info& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(obj_user_info* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.obj_user_info";
  }
  protected:
  explicit obj_user_info(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kIconFieldNumber = 2,
    kLocationFieldNumber = 4,
    kCoinFieldNumber = 3,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string icon = 2;
  void clear_icon();
  const std::string& icon() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_icon(ArgT0&& arg0, ArgT... args);
  std::string* mutable_icon();
  PROTOBUF_NODISCARD std::string* release_icon();
  void set_allocated_icon(std::string* icon);
  private:
  const std::string& _internal_icon() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_icon(const std::string& value);
  std::string* _internal_mutable_icon();
  public:

  // string location = 4;
  void clear_location();
  const std::string& location() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_location(ArgT0&& arg0, ArgT... args);
  std::string* mutable_location();
  PROTOBUF_NODISCARD std::string* release_location();
  void set_allocated_location(std::string* location);
  private:
  const std::string& _internal_location() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_location(const std::string& value);
  std::string* _internal_mutable_location();
  public:

  // int64 coin = 3;
  void clear_coin();
  int64_t coin() const;
  void set_coin(int64_t value);
  private:
  int64_t _internal_coin() const;
  void _internal_set_coin(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:pt.obj_user_info)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icon_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr location_;
  int64_t coin_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class obj_user_game_record final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pt.obj_user_game_record) */ {
 public:
  inline obj_user_game_record() : obj_user_game_record(nullptr) {}
  ~obj_user_game_record() override;
  explicit constexpr obj_user_game_record(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  obj_user_game_record(const obj_user_game_record& from);
  obj_user_game_record(obj_user_game_record&& from) noexcept
    : obj_user_game_record() {
    *this = ::std::move(from);
  }

  inline obj_user_game_record& operator=(const obj_user_game_record& from) {
    CopyFrom(from);
    return *this;
  }
  inline obj_user_game_record& operator=(obj_user_game_record&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const obj_user_game_record& default_instance() {
    return *internal_default_instance();
  }
  static inline const obj_user_game_record* internal_default_instance() {
    return reinterpret_cast<const obj_user_game_record*>(
               &_obj_user_game_record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(obj_user_game_record& a, obj_user_game_record& b) {
    a.Swap(&b);
  }
  inline void Swap(obj_user_game_record* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(obj_user_game_record* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  obj_user_game_record* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<obj_user_game_record>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const obj_user_game_record& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const obj_user_game_record& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(obj_user_game_record* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.obj_user_game_record";
  }
  protected:
  explicit obj_user_game_record(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kKillFieldNumber = 2,
    kDeadFieldNumber = 3,
    kAssistFieldNumber = 4,
  };
  // string time = 1;
  void clear_time();
  const std::string& time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // int32 kill = 2;
  void clear_kill();
  int32_t kill() const;
  void set_kill(int32_t value);
  private:
  int32_t _internal_kill() const;
  void _internal_set_kill(int32_t value);
  public:

  // int32 dead = 3;
  void clear_dead();
  int32_t dead() const;
  void set_dead(int32_t value);
  private:
  int32_t _internal_dead() const;
  void _internal_set_dead(int32_t value);
  public:

  // int32 assist = 4;
  void clear_assist();
  int32_t assist() const;
  void set_assist(int32_t value);
  private:
  int32_t _internal_assist() const;
  void _internal_set_assist(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pt.obj_user_game_record)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
  int32_t kill_;
  int32_t dead_;
  int32_t assist_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class rsp_login final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pt.rsp_login) */ {
 public:
  inline rsp_login() : rsp_login(nullptr) {}
  ~rsp_login() override;
  explicit constexpr rsp_login(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  rsp_login(const rsp_login& from);
  rsp_login(rsp_login&& from) noexcept
    : rsp_login() {
    *this = ::std::move(from);
  }

  inline rsp_login& operator=(const rsp_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline rsp_login& operator=(rsp_login&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const rsp_login& default_instance() {
    return *internal_default_instance();
  }
  static inline const rsp_login* internal_default_instance() {
    return reinterpret_cast<const rsp_login*>(
               &_rsp_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(rsp_login& a, rsp_login& b) {
    a.Swap(&b);
  }
  inline void Swap(rsp_login* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(rsp_login* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  rsp_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<rsp_login>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const rsp_login& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const rsp_login& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(rsp_login* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.rsp_login";
  }
  protected:
  explicit rsp_login(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef rsp_login_RET RET;
  static constexpr RET SUCCESS =
    rsp_login_RET_SUCCESS;
  static constexpr RET ACCOUNT_NULL =
    rsp_login_RET_ACCOUNT_NULL;
  static constexpr RET ACCOUNT_LOCK =
    rsp_login_RET_ACCOUNT_LOCK;
  static constexpr RET PASSWORD_ERROR =
    rsp_login_RET_PASSWORD_ERROR;
  static constexpr RET ERROR =
    rsp_login_RET_ERROR;
  static inline bool RET_IsValid(int value) {
    return rsp_login_RET_IsValid(value);
  }
  static constexpr RET RET_MIN =
    rsp_login_RET_RET_MIN;
  static constexpr RET RET_MAX =
    rsp_login_RET_RET_MAX;
  static constexpr int RET_ARRAYSIZE =
    rsp_login_RET_RET_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  RET_descriptor() {
    return rsp_login_RET_descriptor();
  }
  template<typename T>
  static inline const std::string& RET_Name(T enum_t_value) {
    static_assert(::std::is_same<T, RET>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function RET_Name.");
    return rsp_login_RET_Name(enum_t_value);
  }
  static inline bool RET_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      RET* value) {
    return rsp_login_RET_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kRecordFieldNumber = 3,
    kUserInfoFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // repeated .pt.obj_user_game_record record = 3;
  int record_size() const;
  private:
  int _internal_record_size() const;
  public:
  void clear_record();
  ::pt::obj_user_game_record* mutable_record(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >*
      mutable_record();
  private:
  const ::pt::obj_user_game_record& _internal_record(int index) const;
  ::pt::obj_user_game_record* _internal_add_record();
  public:
  const ::pt::obj_user_game_record& record(int index) const;
  ::pt::obj_user_game_record* add_record();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >&
      record() const;

  // .pt.obj_user_info user_info = 2;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::pt::obj_user_info& user_info() const;
  PROTOBUF_NODISCARD ::pt::obj_user_info* release_user_info();
  ::pt::obj_user_info* mutable_user_info();
  void set_allocated_user_info(::pt::obj_user_info* user_info);
  private:
  const ::pt::obj_user_info& _internal_user_info() const;
  ::pt::obj_user_info* _internal_mutable_user_info();
  public:
  void unsafe_arena_set_allocated_user_info(
      ::pt::obj_user_info* user_info);
  ::pt::obj_user_info* unsafe_arena_release_user_info();

  // int32 ret = 1;
  void clear_ret();
  int32_t ret() const;
  void set_ret(int32_t value);
  private:
  int32_t _internal_ret() const;
  void _internal_set_ret(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:pt.rsp_login)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record > record_;
  ::pt::obj_user_info* user_info_;
  int32_t ret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// req_login

// string username = 1;
inline void req_login::clear_username() {
  username_.ClearToEmpty();
}
inline const std::string& req_login::username() const {
  // @@protoc_insertion_point(field_get:pt.req_login.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void req_login::set_username(ArgT0&& arg0, ArgT... args) {
 
 username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.req_login.username)
}
inline std::string* req_login::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:pt.req_login.username)
  return _s;
}
inline const std::string& req_login::_internal_username() const {
  return username_.Get();
}
inline void req_login::_internal_set_username(const std::string& value) {
  
  username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* req_login::_internal_mutable_username() {
  
  return username_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* req_login::release_username() {
  // @@protoc_insertion_point(field_release:pt.req_login.username)
  return username_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void req_login::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.username)
}

// string password = 2;
inline void req_login::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& req_login::password() const {
  // @@protoc_insertion_point(field_get:pt.req_login.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void req_login::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.req_login.password)
}
inline std::string* req_login::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:pt.req_login.password)
  return _s;
}
inline const std::string& req_login::_internal_password() const {
  return password_.Get();
}
inline void req_login::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* req_login::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* req_login::release_password() {
  // @@protoc_insertion_point(field_release:pt.req_login.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void req_login::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.password)
}

// -------------------------------------------------------------------

// obj_user_info

// string nickname = 1;
inline void obj_user_info::clear_nickname() {
  nickname_.ClearToEmpty();
}
inline const std::string& obj_user_info::nickname() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void obj_user_info::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 nickname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.obj_user_info.nickname)
}
inline std::string* obj_user_info::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.nickname)
  return _s;
}
inline const std::string& obj_user_info::_internal_nickname() const {
  return nickname_.Get();
}
inline void obj_user_info::_internal_set_nickname(const std::string& value) {
  
  nickname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* obj_user_info::_internal_mutable_nickname() {
  
  return nickname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* obj_user_info::release_nickname() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.nickname)
  return nickname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void obj_user_info::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  nickname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nickname,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (nickname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    nickname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.nickname)
}

// string icon = 2;
inline void obj_user_info::clear_icon() {
  icon_.ClearToEmpty();
}
inline const std::string& obj_user_info::icon() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.icon)
  return _internal_icon();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void obj_user_info::set_icon(ArgT0&& arg0, ArgT... args) {
 
 icon_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.obj_user_info.icon)
}
inline std::string* obj_user_info::mutable_icon() {
  std::string* _s = _internal_mutable_icon();
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.icon)
  return _s;
}
inline const std::string& obj_user_info::_internal_icon() const {
  return icon_.Get();
}
inline void obj_user_info::_internal_set_icon(const std::string& value) {
  
  icon_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* obj_user_info::_internal_mutable_icon() {
  
  return icon_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* obj_user_info::release_icon() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.icon)
  return icon_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void obj_user_info::set_allocated_icon(std::string* icon) {
  if (icon != nullptr) {
    
  } else {
    
  }
  icon_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), icon,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (icon_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    icon_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.icon)
}

// int64 coin = 3;
inline void obj_user_info::clear_coin() {
  coin_ = int64_t{0};
}
inline int64_t obj_user_info::_internal_coin() const {
  return coin_;
}
inline int64_t obj_user_info::coin() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.coin)
  return _internal_coin();
}
inline void obj_user_info::_internal_set_coin(int64_t value) {
  
  coin_ = value;
}
inline void obj_user_info::set_coin(int64_t value) {
  _internal_set_coin(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.coin)
}

// string location = 4;
inline void obj_user_info::clear_location() {
  location_.ClearToEmpty();
}
inline const std::string& obj_user_info::location() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.location)
  return _internal_location();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void obj_user_info::set_location(ArgT0&& arg0, ArgT... args) {
 
 location_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.obj_user_info.location)
}
inline std::string* obj_user_info::mutable_location() {
  std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.location)
  return _s;
}
inline const std::string& obj_user_info::_internal_location() const {
  return location_.Get();
}
inline void obj_user_info::_internal_set_location(const std::string& value) {
  
  location_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* obj_user_info::_internal_mutable_location() {
  
  return location_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* obj_user_info::release_location() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.location)
  return location_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void obj_user_info::set_allocated_location(std::string* location) {
  if (location != nullptr) {
    
  } else {
    
  }
  location_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), location,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (location_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    location_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.location)
}

// -------------------------------------------------------------------

// obj_user_game_record

// string time = 1;
inline void obj_user_game_record::clear_time() {
  time_.ClearToEmpty();
}
inline const std::string& obj_user_game_record::time() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.time)
  return _internal_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void obj_user_game_record::set_time(ArgT0&& arg0, ArgT... args) {
 
 time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.time)
}
inline std::string* obj_user_game_record::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:pt.obj_user_game_record.time)
  return _s;
}
inline const std::string& obj_user_game_record::_internal_time() const {
  return time_.Get();
}
inline void obj_user_game_record::_internal_set_time(const std::string& value) {
  
  time_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* obj_user_game_record::_internal_mutable_time() {
  
  return time_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* obj_user_game_record::release_time() {
  // @@protoc_insertion_point(field_release:pt.obj_user_game_record.time)
  return time_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void obj_user_game_record::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  time_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), time,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (time_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    time_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_game_record.time)
}

// int32 kill = 2;
inline void obj_user_game_record::clear_kill() {
  kill_ = 0;
}
inline int32_t obj_user_game_record::_internal_kill() const {
  return kill_;
}
inline int32_t obj_user_game_record::kill() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.kill)
  return _internal_kill();
}
inline void obj_user_game_record::_internal_set_kill(int32_t value) {
  
  kill_ = value;
}
inline void obj_user_game_record::set_kill(int32_t value) {
  _internal_set_kill(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.kill)
}

// int32 dead = 3;
inline void obj_user_game_record::clear_dead() {
  dead_ = 0;
}
inline int32_t obj_user_game_record::_internal_dead() const {
  return dead_;
}
inline int32_t obj_user_game_record::dead() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.dead)
  return _internal_dead();
}
inline void obj_user_game_record::_internal_set_dead(int32_t value) {
  
  dead_ = value;
}
inline void obj_user_game_record::set_dead(int32_t value) {
  _internal_set_dead(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.dead)
}

// int32 assist = 4;
inline void obj_user_game_record::clear_assist() {
  assist_ = 0;
}
inline int32_t obj_user_game_record::_internal_assist() const {
  return assist_;
}
inline int32_t obj_user_game_record::assist() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.assist)
  return _internal_assist();
}
inline void obj_user_game_record::_internal_set_assist(int32_t value) {
  
  assist_ = value;
}
inline void obj_user_game_record::set_assist(int32_t value) {
  _internal_set_assist(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.assist)
}

// -------------------------------------------------------------------

// rsp_login

// int32 ret = 1;
inline void rsp_login::clear_ret() {
  ret_ = 0;
}
inline int32_t rsp_login::_internal_ret() const {
  return ret_;
}
inline int32_t rsp_login::ret() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.ret)
  return _internal_ret();
}
inline void rsp_login::_internal_set_ret(int32_t value) {
  
  ret_ = value;
}
inline void rsp_login::set_ret(int32_t value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:pt.rsp_login.ret)
}

// .pt.obj_user_info user_info = 2;
inline bool rsp_login::_internal_has_user_info() const {
  return this != internal_default_instance() && user_info_ != nullptr;
}
inline bool rsp_login::has_user_info() const {
  return _internal_has_user_info();
}
inline void rsp_login::clear_user_info() {
  if (GetArenaForAllocation() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
}
inline const ::pt::obj_user_info& rsp_login::_internal_user_info() const {
  const ::pt::obj_user_info* p = user_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::pt::obj_user_info&>(
      ::pt::_obj_user_info_default_instance_);
}
inline const ::pt::obj_user_info& rsp_login::user_info() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.user_info)
  return _internal_user_info();
}
inline void rsp_login::unsafe_arena_set_allocated_user_info(
    ::pt::obj_user_info* user_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_info_);
  }
  user_info_ = user_info;
  if (user_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pt.rsp_login.user_info)
}
inline ::pt::obj_user_info* rsp_login::release_user_info() {
  
  ::pt::obj_user_info* temp = user_info_;
  user_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::pt::obj_user_info* rsp_login::unsafe_arena_release_user_info() {
  // @@protoc_insertion_point(field_release:pt.rsp_login.user_info)
  
  ::pt::obj_user_info* temp = user_info_;
  user_info_ = nullptr;
  return temp;
}
inline ::pt::obj_user_info* rsp_login::_internal_mutable_user_info() {
  
  if (user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::pt::obj_user_info>(GetArenaForAllocation());
    user_info_ = p;
  }
  return user_info_;
}
inline ::pt::obj_user_info* rsp_login::mutable_user_info() {
  ::pt::obj_user_info* _msg = _internal_mutable_user_info();
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.user_info)
  return _msg;
}
inline void rsp_login::set_allocated_user_info(::pt::obj_user_info* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete user_info_;
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::pt::obj_user_info>::GetOwningArena(user_info);
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:pt.rsp_login.user_info)
}

// repeated .pt.obj_user_game_record record = 3;
inline int rsp_login::_internal_record_size() const {
  return record_.size();
}
inline int rsp_login::record_size() const {
  return _internal_record_size();
}
inline void rsp_login::clear_record() {
  record_.Clear();
}
inline ::pt::obj_user_game_record* rsp_login::mutable_record(int index) {
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.record)
  return record_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >*
rsp_login::mutable_record() {
  // @@protoc_insertion_point(field_mutable_list:pt.rsp_login.record)
  return &record_;
}
inline const ::pt::obj_user_game_record& rsp_login::_internal_record(int index) const {
  return record_.Get(index);
}
inline const ::pt::obj_user_game_record& rsp_login::record(int index) const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.record)
  return _internal_record(index);
}
inline ::pt::obj_user_game_record* rsp_login::_internal_add_record() {
  return record_.Add();
}
inline ::pt::obj_user_game_record* rsp_login::add_record() {
  ::pt::obj_user_game_record* _add = _internal_add_record();
  // @@protoc_insertion_point(field_add:pt.rsp_login.record)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >&
rsp_login::record() const {
  // @@protoc_insertion_point(field_list:pt.rsp_login.record)
  return record_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pt

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::pt::rsp_login_RET> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pt::rsp_login_RET>() {
  return ::pt::rsp_login_RET_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
