#!/bin/bash
#set -x
#path=`pwd`
insmetaPath="/usr/local/starkv/script"

csudo=""
if command -v sudo > /dev/null; then
    csudo="sudo"
fi

${csudo} chmod -R 744 ${insmetaPath}
cd ${insmetaPath}
${csudo} ./post.sh
