#!/bin/bash

insmetaPath="/usr/local/starkv/script"

csudo=""
if command -v sudo > /dev/null; then
    csudo="sudo"
fi

${csudo} chmod -R 744 ${insmetaPath}  || :
#cd ${insmetaPath}
#${csudo} ./preun.sh
if [ -f ${insmetaPath}/preun.sh ]; then
    cd ${insmetaPath}
    ${csudo} ./preun.sh
else
    bin_link_dir="/usr/bin"
    lib_link_dir="/usr/lib"
    inc_link_dir="/usr/include"
    
    data_link_dir="/usr/local/starkv/data"
    log_link_dir="/usr/local/starkv/log"
    cfg_link_dir="/usr/local/starkv/cfg"

    # Remove all links
    ${csudo} rm -f ${bin_link_dir}/alStarkvServer       || :
    ${csudo} rm -f ${bin_link_dir}/alStarkvClient      || :
    # ${csudo} rm -f ${bin_link_dir}/stardbdemo   || :
    # ${csudo} rm -f ${bin_link_dir}/stardbdump   || :
    # ${csudo} rm -f ${cfg_link_dir}/*          || :
    # ${csudo} rm -f ${inc_link_dir}/stardb.h     || :
    # ${csudo} rm -f ${lib_link_dir}/libstardb.*  || :
    
    ${csudo} rm -f ${log_link_dir}            || :
    ${csudo} rm -f ${data_link_dir}           || :
    
    pid=$(ps -ef | grep "alStarkvServer" | grep -v "grep" | awk '{print $2}')
    if [ -n "$pid" ]; then
        ${csudo} kill -9 $pid   || :
    fi
fi

